version: '3'

services:
  build-lambda:
    build: .
    # Mount /opt folder
    volumes:
      - $PWD/opt:/opt
    environment:
      - NODE_ENV=production
    command: cp -a /tmp/layer.zip opt/layer.zip
